version: '3.1'
services:
  php-apache:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: php-apache-brilo
    ports:
      - "8080:80"
      - "8910:80"
    volumes:
      - ./:/var/www/html
      - .docker/php-apache/logs/apache:/var/log/apache2
      - .docker/php-apache/logs/php:/usr/local/etc/php/log
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf